update [no ci]

diff --git a/.github/actions/after-run-actions/action.yml b/.github/actions/after-run-actions/action.yml
--- a/.github/actions/after-run-actions/action.yml
+++ b/.github/actions/after-run-actions/action.yml
@@ -17,7 +17,17 @@ runs:
       shell: bash
       run: |
           cp ./src/June.Data/bin/Release/net9.0/Data/data.json ./src/myenergy/wwwroot/Data/data.json
+            if [ $? -eq 0 ]; then
+                echo "Copy successful."
+            else
+                echo "Copy failed."
+            fi
           cp ./src/June.Data/bin/Release/net9.0/Data/consolidated.json ./src/myenergy/wwwroot/Data/consolidated.json
+            if [ $? -eq 0 ]; then
+                echo "Copy successful."
+            else
+                echo "Copy failed."
+            fi
           cp ./src/June.Data/bin/Release/net9.0/Data/data.json ./src/June.Data/Data/data.json
             if [ $? -eq 0 ]; then
                 echo "Copy successful."
diff --git a/.github/actions/before-run-actions/action.yml b/.github/actions/before-run-actions/action.yml
--- a/.github/actions/before-run-actions/action.yml
+++ b/.github/actions/before-run-actions/action.yml
@@ -28,6 +28,12 @@ runs:
         else
             echo "Copy failed."
         fi
+        cp ./src/myenergy/wwwroot/Data/consolidated.json ./src/June.Data/Data/consolidated.json
+        if [ $? -eq 0 ]; then
+            echo "Copy successful."
+        else
+            echo "Copy failed."
+        fi
     # Build Data
     - name: Build Data
       shell: bash
